import {
  CalendarSync,
  CreditCard,
  Download,
  // File,
  // FileAudioIcon,
  // FilePen,
  FilePenLine,
  // FileType,
  Flag,
  Folders,
  Guitar,
  Image,
  Languages,
  Layout,
  LayoutDashboard,
  // List,
  ListMusic,
  ListOrdered,
  Mic,
  Music,
  Music2,
  Music3,
  Music4,
  Network,
  // PercentCircle,
  Settings2,
  Smile,
  Speaker,
  Users,
  UserSquare,
  Video,
} from "lucide-react";

export interface ISidebarListType {
  id: number;
  title: string;
  link: string | null;
  icon: React.ReactNode | null;
  children: ISidebarListType[] | null;
}

export const contributorSidebarData: ISidebarListType[] = [
  {
    id: 0,
    title: "Dashboard",
    link: "/contributors/dashboard",
    icon: <LayoutDashboard size={20} />,
    children: null,
  },
  {
    id: 1,
    title: "My Contents",
    link: "#",
    icon: null,
    children: [
      {
        id: 1,
        title: "Tracks",
        link: "/contributors/tracks",
        icon: <Music size={20} />,
        children: null,
      },
      {
        id: 2,
        title: "Sound Banks",
        link: "/contributors/sound-banks",
        icon: <Music2 size={20} />,
        children: null,
      },
      {
        id: 3,
        title: "Sound Effects",
        link: "/contributors/sound-effects",
        icon: <Speaker size={20} />,
        children: null,
      },
      {
        id: 4,
        title: "Presets",
        link: "/contributors/presets",
        icon: <Music4 size={20} />,
        children: null,
      },
      {
        id: 5,
        title: "Files Storage",
        link: "/contributors/file-storage",
        icon: <Folders size={20} />,
        children: null,
      },
      {
        id: 6,
        title: "Photos",
        link: "/contributors/photos",
        icon: <Image size={20} />,
        children: null,
      },
      {
        id: 7,
        title: "Videos",
        link: "/contributors/videos",
        icon: <Video size={20} />,
        children: null,
      },
    ],
  },
  // {
  //   id: 2,
  //   title: "Documents",
  //   link: "#",
  //   icon: null,
  //   children: [
  //     {
  //       id: 1,
  //       title: "License",
  //       link: "/contributors/licenses",
  //       icon: <File size={20} />,
  //       children: null,
  //     },
  //   ],
  // },
  {
    id: 3,
    title: "Account settings",
    link: "#",
    icon: null,
    children: [
      {
        id: 1,
        title: "Account",
        link: "/contributors/account/profile",
        icon: <Layout size={20} />,
        children: null,
      },
      {
        id: 2,
        title: "Social account",
        link: "/contributors/account/social-account",
        icon: <Network size={20} />,
        children: null,
      },
      {
        id: 3,
        title: "Reports",
        link: "/contributors/account/reports",
        icon: <Flag size={20} />,
        children: null,
      },
    ],
  },
];

export const adminSidebarData: ISidebarListType[] = [
  {
    id: 0,
    title: "Dashboard",
    link: "/admin/dashboard",
    icon: <LayoutDashboard size={20} />,
    children: null,
  },
  {
    id: 1,
    title: "Track contents",
    link: "#",
    icon: null,
    children: [
      {
        id: 1,
        title: "Genre",
        link: "/admin/genres",
        icon: <ListMusic size={20} />,
        children: null,
      },
      {
        id: 2,
        title: "Genre Mix",
        link: "/admin/genre-mixes",
        icon: <Music4 size={20} />,
        children: null,
      },
      {
        id: 3,
        title: "Sub Genre",
        link: "/admin/sub-genres",
        icon: <Music2 size={20} />,
        children: null,
      },
      {
        id: 4,
        title: "Key",
        link: "/admin/keys",
        icon: <Music3 size={20} />,
        children: null,
      },
      {
        id: 5,
        title: "Language",
        link: "/admin/languages",
        icon: <Languages size={20} />,
        children: null,
      },
      {
        id: 6,
        title: "Mood Type",
        link: "/admin/mood-types",
        icon: <Smile size={20} />,
        children: null,
      },
      {
        id: 7,
        title: "Instrument",
        link: "/admin/instruments",
        icon: <Guitar size={20} />,
        children: null,
      },
      {
        id: 8,
        title: "Preset Type",
        link: "/admin/preset-types",
        icon: <Mic size={20} />,
        children: null,
      },
    ],
  },
  {
    id: 2,
    title: "Photo Video Content",
    link: "#",
    icon: null,
    children: [
      {
        id: 1,
        title: "Category",
        link: "/admin/photo-video-categories",
        icon: <ListOrdered size={20} />,
        children: null,
      },
    ],
  },
  {
    id: 3,
    title: "Users & Contributors",
    link: "#",
    icon: null,
    children: [
      {
        id: 1,
        title: "Users",
        link: "/admin/users",
        icon: <Users size={20} />,
        children: null,
      },
      {
        id: 2,
        title: "Contributors",
        link: "/admin/contributors",
        icon: <UserSquare size={20} />,
        children: null,
      },
    ],
  },
  // {
  //   id: 4,
  //   title: "System Contents",
  //   link: "#",
  //   icon: null,
  //   children: [
  //     // {
  //     //   id: 1,
  //     //   title: "License Templates",
  //     //   link: "/admin/license-templates",
  //     //   icon: <FileType size={20} />,
  //     //   children: null,
  //     // },
  //     // {
  //     //   id: 2,
  //     //   title: "Pro Packages",
  //     //   link: "/admin/packages",
  //     //   icon: <List size={20} />,
  //     //   children: null,
  //     // },
  //     // {
  //     //   id: 3,
  //     //   title: "Offers",
  //     //   link: "/admin/offers",
  //     //   icon: <PercentCircle size={20} />,
  //     //   children: null,
  //     // },
  //     // {
  //     //   id: 4,
  //     //   title: "Social medias",
  //     //   link: "/admin/social-medias",
  //     //   icon: <Network size={20} />,
  //     //   children: null,
  //     // },
  //   ],
  // },
  {
    id: 5,
    title: "Requests",
    link: "#",
    icon: null,
    children: [
      {
        id: 1,
        title: "Track Requests",
        link: "/admin/track-requests",
        icon: <FilePenLine size={20} />,
        children: null,
      },
      {
        id: 2,
        title: "Reports",
        link: "/admin/reports",
        icon: <Flag size={20} />,
        children: null,
      },
      // {
      //   id: 2,
      //   title: "Sound bank Requests",
      //   link: "/admin/soundbank-requests",
      //   icon: <FilePen size={20} />,
      //   children: null,
      // },
      // {
      //   id: 3,
      //   title: "Preset Requests",
      //   link: "/admin/preset-requests",
      //   icon: <FileAudioIcon size={20} />,
      //   children: null,
      // },
    ],
  },
];

export const userSidebarData: ISidebarListType[] = [
  {
    id: 1,
    title: "Dashboard",
    link: "/users/dashboard",
    icon: <LayoutDashboard size={20} />,
    children: null,
  },
  {
    id: 2,
    title: "Downloads",
    link: "/users/downloads",
    icon: <Download size={20} />,
    children: null,
  },
  {
    id: 3,
    title: "Transactions",
    link: "/users/transactions",
    icon: <CreditCard size={20} />,
    children: null,
  },
  {
    id: 4,
    title: "System",
    link: "#",
    icon: null,
    children: [
      {
        id: 0,
        title: "Subscription",
        link: "/users/system/subscription",
        icon: <CalendarSync size={20} />,
        children: null,
      },
      {
        id: 2,
        title: "Settings",
        link: "/users/system/setting",
        icon: <Settings2 size={20} />,
        children: null,
      },
    ],
  },
];
