export const initialLicenseData: LicenseCreateUpdateFields = {
  licenseName: "",
  licenseShortDescription: "",
  type: "track",
  licenseText: "",
  licenseDefaultPrice: null,
  licenseMinOfferPrice: null,
  audioLicenseDuration: null,
  audioLicenseDistribution: "",
  audioLicenseStreams: "",
  audioLicenseFreeDownloads: "",
  musicVideoMonitizedAmount: "",
  musicVideoNonMonitizedAmount: "",
  musicVideoMonitizedStreamAmount: "",
  musicVideoNonMonitizedStreamAmount: "",
  radioBroadcastRights: true,
  radioStationsAmount: "",
  livePerformanceProfitRights: true,
  livePerformanceNonProfitAmount: "",
  addToMusicByDefault: false,
}
